[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies.work_skipping]
version = "0.1"
path = "../work_skipping"

[dependencies.common]
version = "0.1"
path = "../common"

[dependencies.clap]
version = "4.4.10"
features = ["derive", "cargo"]
